#!/usr/bin/env node
// Append per-album photo-URL rewrite rules to dist/_redirects.
//
// Cloudflare Pages _redirects reliably substitutes :splat (from *) and a
// single named param in destinations, but NOT multiple named params like
// /:p1/:p2/:p3. To avoid that ambiguity we generate one rule per album with
// the destination path hardcoded — `:key` is captured but unused.
//
// Each album gets two rules:
//   /album/path/i-:key       /album/path/index.html   200  (plain photo URL)
//   /album/path/i-:key/*     /album/path/index.html   200  (SmugMug size suffix)

import { readFile, readdir, appendFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dirname, '..');

async function main() {
  const albumsDir = resolve(REPO_ROOT, 'src', 'content', 'albums');
  const files = (await readdir(albumsDir)).filter((f) => f.endsWith('.json'));

  const lines = [
    '',
    '# Per-album photo URL rewrites — generated by generate_photo_redirects.mjs',
    '# Destination paths are hardcoded; :key is captured but not substituted.',
  ];

  for (const f of files) {
    const album = JSON.parse(await readFile(resolve(albumsDir, f), 'utf8'));
    const p = album.url_path; // e.g. /Private/Folder/Album
    const dest = `${p}/index.html`;
    lines.push(`${p}/i-:key      ${dest}   200`);
    lines.push(`${p}/i-:key/*    ${dest}   200`);
  }

  const content = lines.join('\n') + '\n';
  const redirectsPath = resolve(REPO_ROOT, 'dist', '_redirects');
  await appendFile(redirectsPath, content);
  console.log(`✓ appended ${files.length * 2} photo redirect rules to dist/_redirects`);
}

main().catch((err) => {
  console.error('generate_photo_redirects failed:', err);
  process.exit(1);
});
